# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
 use_frameworks!

target 'clubhouse' do
  # Comment the next line if you don't want to use dynamic frameworks
 

  # Pods for clubhouse
  pod 'Firebase'
   pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  

  target 'clubhouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'clubhouseUITests' do
    # Pods for testing
  end

end
